# Generated by Django 4.1.7 on 2023-04-04 12:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0007_rename_recipecommentform_bookcommentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCommentForm',
            new_name='BookCountForm',
        ),
    ]
